/* Blooming — stable cross-device fixes. */
(function(){
  'use strict';
  const $=s=>document.querySelector(s);
  function closeProfileManager(){['#manageProfilesModal','#profileManagerModal','#manageProfiles','#profilesManager','[data-modal="manage-profiles"]'].forEach(s=>document.querySelectorAll(s).forEach(el=>{el.classList.remove('open','show','active','visible');el.setAttribute('aria-hidden','true');el.style.display='none';}));try{if(typeof closeModal==='function')closeModal('manageProfilesModal')}catch(e){}}
  function fixScroll(){let st=$('#blooming-scroll-fix');if(!st){st=document.createElement('style');st.id='blooming-scroll-fix';document.head.appendChild(st)}st.textContent=`@media(min-width:701px){html,body{height:100%;overflow:hidden!important}#app{height:100vh!important;overflow:hidden!important}.sh{height:100vh!important;min-height:0!important}.nv{position:sticky!important;top:0!important;height:100vh!important;overflow:hidden!important}.rc{position:sticky!important;top:0!important;height:100vh!important;overflow:auto!important}main{height:100vh!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important}}@media(max-width:700px){html,body{height:auto!important;overflow-x:hidden!important;overflow-y:auto!important}#app,.sh{height:auto!important;min-height:100vh!important;overflow:visible!important}.sh{display:block!important}.nv{position:fixed!important;left:0!important;right:0!important;bottom:0!important;top:auto!important;width:100%!important;height:auto!important;z-index:1000!important;display:flex!important;flex-direction:row!important;justify-content:space-around!important}.nv .lg,.nv .b,.nv .me{display:none!important}.nv a,.nv button.l{flex:1!important;justify-content:center!important;padding:10px 6px!important}.nv a span,.nv button.l span{display:none!important}main{height:auto!important;min-height:100vh!important;overflow:visible!important;padding-bottom:76px!important}.rc{display:none!important}}`}
  function persistLocal(){try{if(typeof saveLocalOnly==='function')saveLocalOnly()}catch(e){}}
  async function syncProfile(id){try{if(!id||typeof S==='undefined'||!S.u||!S.u[id])return;if(typeof CLOUD_ON==='undefined'||!CLOUD_ON||typeof SB==='undefined'||!SB)return;const u=S.u[id];let accountId=u.accountId||null;try{const a=typeof currentAccount==='function'?currentAccount():null;if(a&&a.id)accountId=typeof cloudAccountId==='function'?cloudAccountId(a.id):a.id}catch(e){}if(!accountId)return;const row={id:u.id,account_id:accountId,nome:u.nome||'Perfil',username:u.user||'',bio:u.bio||'',loc:u.loc||'',cor:u.cor||'#E8336F',emo:u.emo||'🌸',foto:u.foto||'',capa:u.capa||'',verificado:!!u.verificado,privada:!!u.privada,seg:+u.seg||0,sgd:+u.sgd||0};const r=await SB.from('blooming_profiles').upsert(row,{onConflict:'id'});if(r&&r.error)throw r.error;u.accountId=accountId;persistLocal()}catch(e){console.warn('Blooming profile cloud save failed',e)}}
  function bindProfileEditor(){if(window.__bloomingEditorFix)return;window.__bloomingEditorFix=true;const oldEdit=window.editU;if(typeof oldEdit==='function'){window.editU=function(id){window.__bloomingEditingProfileId=id||window.S?.me||null;return oldEdit.apply(this,arguments)}}document.addEventListener('click',function(e){const save=e.target.closest&&e.target.closest('#md [data-m="s"]');if(!save)return;const id=window.__bloomingEditingProfileId||window.S?.me;setTimeout(()=>syncProfile(id),350)},true)}
  async function pullProfiles(){try{if(typeof CLOUD_ON==='undefined'||!CLOUD_ON||typeof SB==='undefined'||!SB||typeof S==='undefined'||!S.u)return;const r=await SB.from('blooming_profiles').select('*');if(r.error||!Array.isArray(r.data))return;r.data.forEach(row=>{const u=S.u[row.id];if(!u)return;u.accountId=row.account_id||u.accountId;if(row.nome!=null)u.nome=row.nome;if(row.username!=null)u.user=row.username;if(row.bio!=null)u.bio=row.bio;if(row.loc!=null)u.loc=row.loc;if(row.cor!=null)u.cor=row.cor;if(row.emo!=null)u.emo=row.emo;if(row.foto!=null)u.foto=row.foto;if(row.capa!=null)u.capa=row.capa;if(row.verificado!=null)u.verificado=!!row.verificado;if(row.privada!=null)u.privada=!!row.privada;if(row.seg!=null)u.seg=+row.seg||0;if(row.sgd!=null)u.sgd=+row.sgd||0});persistLocal();try{if(typeof view==='function')view()}catch(e){}}catch(e){console.warn('Blooming remote profile refresh failed',e)}}
  function reconcileAccounts(){try{if(!S.accounts||!S.u)return;Object.values(S.accounts).forEach(a=>a.profiles=[]);Object.values(S.u).forEach(u=>{if(!u||!u.accountId)return;if(!S.accounts[u.accountId])S.accounts[u.accountId]={id:u.accountId,nome:u.nome||'Conta',pw:'',profiles:[]};const a=S.accounts[u.accountId];a.profiles=a.profiles||[];if(!a.profiles.includes(u.id))a.profiles.push(u.id)});persistLocal()}catch(e){console.warn('Blooming account reconciliation',e)}}
  function removeGenericLocalPosts(){try{if(!Array.isArray(S.posts))return;const bad=/^(demo_|test_|seed_|generic_)/i;S.posts=S.posts.filter(p=>{if(!p)return false;if(p.generated===true||p.generic===true||p.demo===true||p.test===true||p.seed===true)return false;if(bad.test(String(p.id||'')))return false;const t=String(p.text||p.t||'').toLowerCase();if(/4\s*horas?.*(costur|fantasia)/i.test(t))return false;return true});persistLocal()}catch(e){console.warn('Blooming generic-post cleanup',e)}}
  function disableGenericAutomation(){try{if(typeof window.runAutomations!=='function'||window.__bloomingAutomationFix)return;window.__bloomingAutomationFix=true;window.runAutomations=function(){if(typeof S==='undefined'||!S.u)return;Object.values(S.u).forEach(u=>{if(u&&u.xSync&&u.xSync.enabled&&typeof syncXProfile==='function'){const gap=(+u.xSync.interval||5)*60000;if(!u.xSync.lastSync||Date.now()-u.xSync.lastSync>=gap)syncXProfile(u.id,true)}});removeGenericLocalPosts()};removeGenericLocalPosts()}catch(e){console.warn('Blooming automation fix',e)}}
  function patchCloudPull(){if(typeof window.cloudPull!=='function'||window.__bloomingCloudPullFix)return;window.__bloomingCloudPullFix=true;const old=window.cloudPull;window.cloudPull=async function(){const result=await old.apply(this,arguments);reconcileAccounts();await pullProfiles();removeGenericLocalPosts();return result}}
  function init(){fixScroll();bindProfileEditor();disableGenericAutomation();patchCloudPull();document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('[data-m="x"]');if(b&&b.closest('#md')){e.preventDefault();e.stopPropagation();try{$('#md').close()}catch(x){}}},true);document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('#manageProfilesModal .close,#manageProfilesModal .modal-close,#profileManagerModal .close');if(b){e.preventDefault();e.stopPropagation();closeProfileManager()}},true);setTimeout(()=>{fixScroll();bindProfileEditor();disableGenericAutomation();patchCloudPull()},800);setTimeout(()=>{fixScroll();bindProfileEditor();disableGenericAutomation();patchCloudPull()},2500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
