/* Blooming — stable fixes + post date/time + media visual fixes */
(function(){
'use strict';
const $=s=>document.querySelector(s);
const safe=fn=>{try{return fn()}catch(e){console.warn('Blooming fix:',e)}};
function save(){safe(()=>typeof saveLocalOnly==='function'&&saveLocalOnly())}
function closeProfileManager(){['#manageProfilesModal','#profileManagerModal','#manageProfiles','[data-modal="manage-profiles"]'].forEach(s=>document.querySelectorAll(s).forEach(el=>{el.classList.remove('open','show','active','visible');el.setAttribute('aria-hidden','true');el.style.display='none'}));safe(()=>typeof closeModal==='function'&&closeModal('manageProfilesModal'))}
function scrollFix(){let x=$('#blooming-scroll-fix');if(!x){x=document.createElement('style');x.id='blooming-scroll-fix';document.head.appendChild(x)}x.textContent=`@media(min-width:701px){html,body{height:100%;overflow:hidden!important}#app{height:100vh!important;overflow:hidden!important}.sh{height:100vh!important;min-height:0!important}.nv{position:sticky!important;top:0!important;height:100vh!important;overflow:hidden!important}.rc{position:sticky!important;top:0!important;height:100vh!important;overflow:auto!important}main{height:100vh!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important}}@media(max-width:700px){html,body{height:auto!important;overflow-x:hidden!important;overflow-y:auto!important}#app,.sh{height:auto!important;min-height:100vh!important;overflow:visible!important}.sh{display:block!important}.nv{position:fixed!important;left:0!important;right:0!important;bottom:0!important;top:auto!important;width:100%!important;height:auto!important;z-index:1000!important;display:flex!important;flex-direction:row!important;justify-content:space-around!important}.nv .lg,.nv .b,.nv .me{display:none!important}.nv a,.nv button.l{flex:1!important;justify-content:center!important;padding:10px 6px!important}.nv a span,.nv button.l span{display:none!important}main{height:auto!important;min-height:100vh!important;overflow:visible!important;padding-bottom:76px!important}.rc{display:none!important}}`}
function removeGeneric(){safe(()=>{if(!Array.isArray(S.posts))return;const bad=/^(demo_|test_|seed_|generic_)/i;S.posts=S.posts.filter(p=>p&&p.generated!==true&&p.generic!==true&&p.demo!==true&&p.test!==true&&p.seed!==true&&!bad.test(String(p.id||''))&&!/4\s*horas?.*(costur|fantasia)/i.test(String(p.text||p.t||'')));save()})}
function reconcile(){safe(()=>{if(!S.accounts||!S.u)return;Object.values(S.accounts).forEach(a=>a.profiles=[]);Object.values(S.u).forEach(u=>{if(!u||!u.accountId)return;if(!S.accounts[u.accountId])S.accounts[u.accountId]={id:u.accountId,nome:u.nome||'Conta',pw:'',profiles:[]};const a=S.accounts[u.accountId];a.profiles=a.profiles||[];if(!a.profiles.includes(u.id))a.profiles.push(u.id)});save()})}
async function pullProfiles(){try{if(typeof CLOUD_ON==='undefined'||!CLOUD_ON||typeof SB==='undefined'||!SB||typeof S==='undefined'||!S.u)return;const r=await SB.from('blooming_profiles').select('*');if(r.error||!Array.isArray(r.data))return;r.data.forEach(row=>{const u=S.u[row.id];if(!u)return;u.accountId=row.account_id||u.accountId;['nome','username','bio','loc','cor','emo','foto','capa'].forEach(k=>{const target=k==='username'?'user':k;if(row[k]!=null)u[target]=row[k]});if(row.verificado!=null)u.verificado=!!row.verificado;if(row.privada!=null)u.privada=!!row.privada;if(row.seg!=null)u.seg=+row.seg||0;if(row.sgd!=null)u.sgd=+row.sgd||0});save();safe(()=>typeof view==='function'&&view())}catch(e){console.warn('profile refresh failed',e)}}
function patchCloud(){if(typeof window.cloudPull!=='function'||window.__bloomingCloudPullFix)return;window.__bloomingCloudPullFix=true;const old=window.cloudPull;window.cloudPull=async function(){const r=await old.apply(this,arguments);reconcile();await pullProfiles();removeGeneric();return r}}
function setPostDate(p,iso){if(!p||!iso)return;const d=new Date(iso);if(isNaN(d.getTime()))return;const v=d.toISOString();p.publishedAt=v;p.createdAt=v;p.created_at=v;p.ts=d.getTime();p.date=v;p.time=v}
function postTime(p){const vals=[p&&p.publishedAt,p&&p.createdAt,p&&p.created_at,p&&p.date,p&&p.time,p&&p.ts,p&&p.timestamp];for(const v of vals){if(v==null||v==='')continue;const d=typeof v==='number'?new Date(v):new Date(v);if(!isNaN(d.getTime()))return d.getTime()}return 0}
function sortPosts(){safe(()=>{if(!Array.isArray(S.posts))return;S.posts.sort((a,b)=>postTime(b)-postTime(a));save()})}
function dateControls(){if(!$('#md')||$('#blooming-post-date'))return;const modal=$('#md');const ta=modal.querySelector('textarea');if(!ta)return;const box=document.createElement('div');box.id='blooming-post-date';box.style.cssText='margin:10px 0;padding:12px;border:1px solid var(--line);border-radius:14px;background:var(--card)';box.innerHTML='<b>Data e hora da publicação</b><label style="display:block;margin-top:8px">Data<input id="bloomingPostDate" type="date" class="fi"></label><label style="display:block">Hora<input id="bloomingPostTime" type="time" class="fi"></label><label style="display:flex;gap:8px;align-items:center"><input id="bloomingPostNow" type="checkbox" checked> Usar data e hora atuais</label>';ta.insertAdjacentElement('afterend',box);const now=new Date();$('#bloomingPostDate').value=now.toISOString().slice(0,10);$('#bloomingPostTime').value=now.toTimeString().slice(0,5);$('#bloomingPostNow').onchange=e=>{if(e.target.checked){const n=new Date();$('#bloomingPostDate').value=n.toISOString().slice(0,10);$('#bloomingPostTime').value=n.toTimeString().slice(0,5)}}}
function selectedDate(){const now=$('#bloomingPostNow');if(now&&now.checked)return new Date().toISOString();const d=$('#bloomingPostDate')?.value,t=$('#bloomingPostTime')?.value;if(!d||!t)return new Date().toISOString();return new Date(d+'T'+t).toISOString()}
function datePatch(){if(window.__bloomingDatePatch)return;window.__bloomingDatePatch=true;const originalEdit=window.editPost;if(typeof originalEdit==='function'){window.editPost=function(id){const r=originalEdit.apply(this,arguments);setTimeout(()=>{dateControls();const p=S.posts?.find(x=>x.id===id);if(p){const d=new Date(postTime(p)||Date.now());if($('#bloomingPostDate'))$('#bloomingPostDate').value=d.toISOString().slice(0,10);if($('#bloomingPostTime'))$('#bloomingPostTime').value=d.toTimeString().slice(0,5);if($('#bloomingPostNow'))$('#bloomingPostNow').checked=false}},30);return r}}
 document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('[data-m="s"]');if(!b)return;const modal=b.closest('#md');if(!modal)return;const ta=modal.querySelector('textarea');if(!ta)return;const pending={text:ta.value,date:selectedDate()};setTimeout(()=>{if(!Array.isArray(S.posts))return;const matches=S.posts.filter(p=>String(p.t||p.text||'')===String(pending.text));const p=matches[matches.length-1];if(p){setPostDate(p,pending.date);sortPosts();save();safe(()=>typeof cloudPush==='function'&&cloudPush())}},500)},true);
 const mo=new MutationObserver(()=>{if($('#md')&&!$('#blooming-post-date'))dateControls()});mo.observe(document.body,{childList:true,subtree:true});setTimeout(sortPosts,1000)}
function mediaVisualFix(){if($('#blooming-media-visual-fix'))return;const s=document.createElement('style');s.id='blooming-media-visual-fix';s.textContent=`/* Fixed post marker: always top-right of the post/profile media container. */
.po,.single,.pf{position:relative}
.po .pinned,.po [data-pinned="true"],.po .pin,.single .pinned,.single [data-pinned="true"],.single .pin{position:absolute!important;top:10px!important;right:12px!important;left:auto!important;bottom:auto!important;z-index:8!important;margin:0!important}
/* Video media is borderless, including the publish preview and the feed. */
.media-preview video,.media-preview .mi video,.gallery .gi video,.po video,.single video{border:0!important;outline:0!important;box-shadow:none!important;border-radius:0!important}
/* Keep the video itself borderless while allowing the surrounding gallery to retain its layout. */
.gallery .gi:has(video){border:0!important}
.media-preview .mi:has(video){border:0!important}
`;document.head.appendChild(s)}
function init(){scrollFix();patchCloud();removeGeneric();datePatch();mediaVisualFix();document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('[data-m="x"]');if(b&&b.closest('#md')){e.preventDefault();e.stopPropagation();safe(()=>$('#md').close())}},true);document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('#manageProfilesModal .close,#manageProfilesModal .modal-close,#profileManagerModal .close');if(b){e.preventDefault();e.stopPropagation();closeProfileManager()}},true);setTimeout(()=>{scrollFix();patchCloud();datePatch();mediaVisualFix();sortPosts()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
